name: CI

permissions:
  checks: write

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - "logisim/**"
      - "cocas/**"
      - "cocoemu/**"
      - "tests/**"
  pull_request:
    branches: [ "master" ]
    paths:
      - "logisim/**"
      - "cocas/**"
      - "cocoemu/**"
      - "tests/**"

jobs:
  test:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install package and dependencies
        run: pip install ruff pytest strictyaml -e .

      - name: Prepare test environment
        run: make prepare_tests

      - name: Test with pytest
        run: pytest --tb=no -rA -v --junitxml tests/results/result.xml

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Results
          path: tests/results/result.xml
          reporter: java-junit
